### ISSUE TITLE
Bump analyzer to v5

### ISSUE THREAD

**Issue by GZGavinZhao** [angulardart-community/angular#32]
Previously we just add `deprecated_member_use: ignore` to the `analysis_options.yaml` file in the monorepo root. Now `analyzer` has gone to v5 so the usage of deprecated APIs must be dealt with now.

The hardest parts are the last three, since they change the class returned or require another variable, so likely we'll have to work around them.

- [x] Replace `getType` with `getClass` for `LibraryCompilationUnitElement` and `LibraryElement`.
- [ ] Replace `name` with `getDisplayString` for `DartType`. **Note:** need to think about whether nullability
- [x] Replace `element` with `element2`. Note that the return type changes from `ClassElement` to `InterfaceElement`, so it requires a bit more work. Most times we should be able to just cast it to `ClassElement` since `ClassElement` implements `InterfaceElement`.
- [x] Replace `enclosingElement` with `enclosingElement3`.
- [x] Somehow replace `resolveToBound` from `DartType` with `TypeSystem`'s _instance_ method `resolveToBound`.
- [ ] Replace `parts` (`CompilationUnitElement`) with `parts2` (`PartsElement`) from `LibraryElement`.
- [ ] Replace `import` (`ImportElement`) with `imports2` (`LibraryInputElement`) from `LibraryElement`.

**Comment by denniskaselow** [comment]
> Replace element with element2. Note that the return type changes from ClassElement to InterfaceElement, so it requires a bit more work. Most times we should be able to just cast it to ClassElement since ClassElement implements InterfaceElement.

FYI in case you want to migrate to the current version of analyzer and plan to have no lints about deprecated members: with [analyzer 5.2](https://pub.dev/packages/analyzer/changelog#520) `element2` is deprecated and `element` is the new one (The old `element` is removed in 5.0).

**Comment by GZGavinZhao** [comment]
Yeah, so my process will be:
1. Migrate deprecated API's in analyzer v4
2. Upgrade analyzer to v5, ensure everything is still working
3. Migrate deprecated API's again
4. Then I'll probably have to repeat these steps for analyzer v6

As I might've said previously, unfortunately the analyzer is probably one of the most tiresome packages to keep up-to-date with.

**Comment by ykmnkmi** [comment]
Any progress? I'm now doing the same, fixing all static analysis warnings and upgrading to the new `analyzer`.

**Comment by GZGavinZhao** [comment]
Sorry, not really. It's the busiest time of the year for me and I've been having a bad cold/flu. I am blocked on the resolveToBound issue, particularly with the case when dartType is FunctionType (see where resolveToBound is defined).

**Comment by GZGavinZhao** [comment]
@ykmnkmi Also, I'm absolutely okay if you want to use the existing changes in your PR. You don't need to let me know.

**Comment by GZGavinZhao** [comment]
Fixed by #37.
