### ISSUE TITLE
New library names to publish forked by AngularDart Community packages

### ISSUE THREAD

**Issue by IgorBabalich** [angulardart-community/angular#7]
This task is a part of [AngularDart 8 Roadmap](https://github.com/angulardart-community/angular/issues/6) 

Rename forked by AngularDart Community packages to be able publish and use them on pub.dev

New package names:
angular -> ngdart (the existing ngdart package utility will be renamed to ngdart_cli)
angular_ast  -> ngast
angular_compiler -> ngcompiler
angular_forms -> ngforms
angular_router -> ngrouter
angular_test -> ngtest

Dart SDK: 2.17.0
AngularDart Version: 8.0.0

**Comment by GZGavinZhao** [comment]
Go ahead :)
